services:
  - type: web
    name: neptronix-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ADMIN_EMAIL
        value: admin@neptronix.com
      - key: CORS_ORIGIN
        sync: false
